# Generated by Django 4.1 on 2024-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nazwa_marki', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='iamges')),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osprzęt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Konfiguracja_osprzętu', models.CharField(max_length=100)),
                ('Materiał_ramy', models.CharField(max_length=100)),
                ('Widelec', models.CharField(max_length=100)),
                ('Damper', models.CharField(max_length=100)),
                ('Przerzutki', models.CharField(max_length=100)),
                ('Opony', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Typ_roweru', models.CharField(max_length=100)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_roweru', models.CharField(max_length=100)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
                ('Typ', models.ManyToManyField(to='www.typ')),
                ('osprzęt', models.ManyToManyField(to='www.osprzęt')),
            ],
        ),
    ]
